##
 # Copyright OpenSearch Contributors
 # SPDX-License-Identifier: Apache-2.0
##
 
name: Test and Build Notifications

on: [push, pull_request]

jobs:
  build:
    strategy:
      # This setting says that all jobs should finish, even if one fails
      fail-fast: false
      matrix:
        java: [11, 17]

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # notifications
      - name: Checkout Notifications
        uses: actions/checkout@v2

      # Temporarily exclude tests which causing CI to fail. Tracking in #251
      - name: Build with Gradle
        run: |
          cd notifications
          ./gradlew build -PexcludeTests="**/SesChannelIT*"

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: opensearch-notifications
          directory: notifications/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p notifications-build/{notifications,notifications-core}
          cp -r ./notifications/notifications/build/distributions/*.zip notifications-build/notifications/
          cp -r ./notifications/core/build/distributions/*.zip notifications-build/notifications-core/

      - name: Upload Artifacts for notifications plugin
        uses: actions/upload-artifact@v1
        with:
          name: notifications-plugin
          path: notifications-build/notifications

      - name: Upload Artifacts for notifications-core plugin
        uses: actions/upload-artifact@v1
        with:
          name: notifications-core-plugin
          path: notifications-build/notifications-core
